name: Swift

on:
  push:
    branches: [ "Branch-1" ]
  pull_request:
    branches: [ "Branch-1" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'
        
      - name: Install Dependencies
        run: |
          if [ -f "Podfile" ]; then
            gem install cocoapods
            pod install
          fi

      - name: Build and Archive
        run: |
          xcodebuild clean archive \
            -workspace "CI_CD_Demo.xcworkspace" \
            -scheme CI_CD_Demo \
            -sdk iphoneos \
            -archivePath ./build/CI_CD_Demo.xcarchive \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath ./build/CI_CD_Demo.xcarchive \
            -exportOptionsPlist ./ExportOptions.plist \
            -exportPath ./build

      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CI_CD_Demo.ipa
          path: "CI_CD_Demo/build/*.ipa"
